# Generated by Django 3.1.3 on 2023-08-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anser',
            new_name='Answer',
        ),
    ]
